server:
  port: 9001
dubbo:
  application:
    name: site-service-boot-provider
  registry:
    address: zookeeper://192.168.88.11:2181
  protocols:
    protocol1:
      id: rest
      name: rest
      port: 8083
      host: 0.0.0.0
    protocol2:
      id: dubbo2
      name: dubbo
      port: 20883
      host: 0.0.0.0
#  protocol:
#    name: dubbo
#    port: 20882